# General Jekyll Config
theme: jekyll-theme-minimal
title: Welcome to Moon
show_downloads: false
logo: pics/logo.png
description: " My name is Ivy Wu. There are three things that are important to me: bed, computer, peanut butter. MOON contains a collection of my previous works and some random thoughts. You are more than welcome to have a space journey. :rocket: "
google_analytics: UA-127038309-1
plugins:
  - jemoji
markdown: kramdown
mathjax: true
permalink: /blog/:year/:month/:day/:title
